# version: '3.8'
services:
  lb:
    image: nginx
    container_name: nginx_lb
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ws1
      - ws2
      - ws3
      - ws4
    networks:
      - chat_net
  rs:
    image: redis
    container_name: chat_redis
    ports:
    - "6379:6379"
    volumes:
      - redis_v:/data
    networks:
      - chat_net
  db:
    image: mongo
    container_name: chat_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_v:/data/db
    depends_on:
      - rs
    networks:
      - chat_net
  ws1:
    container_name: ws1
    image: chat_server
    depends_on:
      - rs
      - db
    env_file:
      - ./.env
    networks:
      - chat_net
    environment:
      - MONGO_URI=mongodb://chat_mongo:27017/quizapp
      - REDIS_URI=redis://rs:6379
  ws2:
    container_name: ws2
    image: chat_server
    depends_on:
      - rs
      - db
    env_file:
      - ./.env
    networks:
      - chat_net
    environment:
      - MONGO_URI=mongodb://chat_mongo:27017/quizapp
      - REDIS_URI=redis://rs:6379
  ws3:
    container_name: ws3
    image: chat_server
    depends_on:
      - rs
      - db
    env_file:
      - ./.env
    networks:
      - chat_net
    environment:
      - MONGO_URI=mongodb://chat_mongo:27017/quizapp
      - REDIS_URI=redis://rs:6379
  ws4:
    container_name: ws4
    image: chat_server
    depends_on:
      - rs
      - db
    env_file:
      - ./.env
    networks:
      - chat_net
    environment:
      - MONGO_URI=mongodb://chat_mongo:27017/quizapp
      - REDIS_URI=redis://rs:6379
volumes:
  mongo_v:
  redis_v:
networks:
  chat_net:
    driver: bridge
  